apiVersion: v1
kind: Service
metadata:
  name: identity-api
  namespace: identity-api
  labels:
    app: identity-api
spec:
  type: LoadBalancer
  selector:
    app: identity-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
